# https://github.com/chezmoi/dotfiles

name: ci

on:
  push:
  pull_request:

jobs:
  clone-and-install:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/vscode/devcontainers/base:ubuntu
      env:
        CODESPACES: true
    steps:
      - uses: actions/checkout@v2
      - run: |
          chmod a+x ./bootstrap.sh
          ./bootstrap.sh
      - name: chezmoi data
        run: '"$HOME/.local/bin/chezmoi" data'
